server:
  port: 9000

spring:
  application:
    name: carrotMarket

  datasource:
    platform: mysql
    url: jdbc:mysql://database-1.cwipvykherjc.ap-northeast-2.rds.amazonaws.com/CarrotMarket


    username: admin
    password: sokite1017!
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql 8버전
    # driver-class-name: com.mysql.jdbc.Driver # mysql 5버전


  jpa:
    properties:
      hibernate:
        show_sql: true
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        #테이블 칼럼명 - 카멜케이스
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
